### PR TITLE
Unhandled rejections #313

### LINKED ISSUE #313: Unhandled rejections
**Describe the bug**
Unhandled rejections

Screen Shot 2019-12-05 at 1 10 18 PM

### PR DESCRIPTION
**Pull request by Wolfy64**
close #313 

If you are ok this solution I will extends it on other `Promises`

### CODE REVIEW

File: src/server/server.ts [hunk 1]
```diff
@@ -82,7 +82,7 @@ const startAppServer = (
       console.log(cyan, `myProxy is running on port ${port}!`)
       resolve(server)
     })
-  })
+  }).catch(error => console.error(`startAppServer: ${error}`))
```
Comment (songz) [inline src/server/server.ts]: this is triggering the `new Promise` object so we should be catching here.

Comment (songz) [reply src/server/server.ts]: instead, update `src/app.js` where this function is being called, and promise is being returned.
