### PR TITLE
Git issue 266

### LINKED ISSUE #266: [MAJOR BLOCKER] SETUP does not work
**Describe the bug**
setup screen

Clicking on `setUp` during development should properly setup the domain name (skip ssl cert generation and domain setup)

Currently it does not properly setup the domain name... AT ALL during development.

**To Reproduce**
1. Run the app locally (or on your dev server) without NODE_ENV=production flag.
2. Go to `/admin` and click on setup.
3. Setup doesn't work. Expected behavior: domain should be in `availableDomains`, and users should see a checkmark saying the domain has been setup.

**Expected behavior**
Domain should be in `availableDomains`, and users should see a checkmark saying the domain has been setup.

### PR DESCRIPTION
**Pull request by Wolfy64**
close #266

### CODE REVIEW

File: src/server/server.ts [hunk 1]
```diff
@@ -15,15 +15,15 @@ import { ProxyMapping } from '../types/general'
 
 const cyan = '\x1b[36m\u001b[1m%s\x1b[0m'
 const red = '\x1b[31m\u001b[1m%s\x1b[0m'
+const warningMsg = 'WARNING! You have to setup ADMIN password first before to run the app.'
```
Comment (songz) [inline src/server/server.ts]: this is an error. `ERROR: App cannot be started because you must set an ADMIN password in the environment variable when running this app. Visit https://github.com/garageScript/myproxy` <- should link to the correct section in readme.

File: src/helpers/dotEnv.ts [hunk 2]
```diff
@@ -0,0 +1,6 @@
+export default {
+  ENV: process.env.NODE_ENV || 'development',
```
Comment (songz) [inline src/helpers/dotEnv.ts]: I think we should also do `ENV`. `process.env.NODE_ENV || process.env.ENV || 'development`

File: src/helpers/dotEnv.ts [hunk 3]
```diff
@@ -0,0 +1,6 @@
...
+  PORT: process.env.PORT || 3000,
+  ADMIN_PASS: process.env.ADMIN || null,
+  HOME: process.env.HOME || null,
```
Comment (songz) [inline src/helpers/dotEnv.ts]: from my professional experience, its better to also have helper functions.... like `isProduction`

File: src/app.ts [hunk 4]
```diff
@@ -1,6 +1,13 @@
...
+const { PORT, ADMIN_PASS, ENV, HOME } = dotEnv
+
+startAppServer(PORT, ADMIN_PASS)
+
+/**
+ * Proxy Server will create SSL Certificates on the server
+ * for your domains in production.
+ * Development mode do not have to run the proxy server.
+ * */
+if (ENV === 'production') startProxyServer(HOME)
```
Comment (songz) [inline src/app.ts]: Personally, I avoid hard coded strings. Since you are refactoring the `env` file. could we just import `isProduction` function an run that? `if (isProduction())`

File: src/api/admin.ts [hunk 5]
```diff
@@ -14,13 +17,16 @@ app.post('/sslCerts', async (req, res) => {
...
   }
+
   try {
-    const sslCertResponse = await createSslCerts(
-      serviceResponse,
-      service,
-      selectedDomain
-    )
-    if (!sslCertResponse.success) return res.json(sslCertResponse)
+    if(ENV === 'production'){
```
Comment (songz) [inline src/api/admin.ts]: `isProduction`. Read comment below.

File: src/api/admin.ts [hunk 6]
```diff
@@ -14,13 +17,16 @@ app.post('/sslCerts', async (req, res) => {
...
+      const sslCertResponse = await createSslCerts(
+        serviceResponse,
+        service,
+        selectedDomain
+      )
+      if (!sslCertResponse.success) return res.json(sslCertResponse)
+    }
 
     const cnameResponse = await setCnameRecords(
```
Comment (songz) [inline src/api/admin.ts]: could you also add a check here.... to only setCnameRecords if we are in production?
