### PR TITLE
close #82 and fixes Bug when domains are not Authorized

### LINKED ISSUE #82: When new provider keys are created / updated, refresh the page
CUrrently, after updating or creating, there's 0 feedback so I have no idea what happened. (is it successful?)

### PR DESCRIPTION
**Pull request by SahilKalra98**

### CODE REVIEW

File: src/public/providers.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ type Provider = {
   service: string
   keys: Array<ProviderKey>
   // eslint-disable-next-line
-  domains: Array<any>
+  domains: any
```
Comment (songz) [inline src/public/providers.ts]: domains should be an array right?

File: src/public/providers.ts [hunk 2]
```diff
@@ -97,7 +102,9 @@ class ProviderElement {
         providerKeysContainer
       )
     })
-    provider.domains.map(domain => {
+    const isAuthorized = !provider.domains.code ? true : false
```
Comment (songz) [inline src/public/providers.ts]: what is this doing?

File: src/public/providers.ts [hunk 3]
```diff
@@ -97,7 +102,9 @@ class ProviderElement {
...
+    const providerDomains = isAuthorized ? provider.domains : []
```
Comment (songz) [inline src/public/providers.ts]: why do we need this? `/api/admin/providers` should always be be returning an array of domains. If its not, then the fix must go in at the api endpoint to return `[]` if domains does not exist.

File: src/public/providers.ts [hunk 4]
```diff
@@ -64,7 +69,7 @@ class ProviderKeyElement {
         headers: {
           'Content-Type': 'application/json'
         }
-      })
+      }).then(() => window.location.reload())
```
Comment (songz) [inline src/public/providers.ts]: instead of reloading the page, should we have a `render` function so that we are consistent with implementation across different pages? For example, the `render` function in this PR: https://github.com/garageScript/myProxy/pull/91/files

File: src/api/admin.ts [hunk 5]
```diff
@@ -123,7 +123,12 @@ app.patch('/providerKeys/:id', (req, res) => {
 
 app.get('/providers', async (_, res) => {
   const data = await Promise.all([goDaddy.getDomains()])
-  return res.json(data) // Data send to view providers ?
+  console.log(data)
```
Comment (songz) [inline src/api/admin.ts]: remove
