### PR TITLE
Bug: SSL Cert needs to send two commands for *.domain and .domain

### LINKED ISSUE #102: Bug: SSL Cert needs to send two commands for  *.domain and .domain

### PR DESCRIPTION
**Pull request by Wolfy64**
Fix #102 
After reading the doc, if I don't misunderstand the first parameter has to be the **Main_domain** other parameters are **SAN_Domains**.
I can't test it due to the limitation as 5 by week however I can run `acme.sh --list` that show the list

### CODE REVIEW

File: src/api/admin.ts [hunk 1]
```diff
@@ -26,7 +26,7 @@ app.post('/sslCerts', async (req, res) => {
       return acc + `${key}=${value} `
     }, '')
     const { stderr } = await exec(
-      `${envVars} ./acme.sh/acme.sh --issue --dns ${service} -d "*.${selectedDomain}" -d ${selectedDomain} --force`
+      `${envVars} ./acme.sh/acme.sh --issue --dns ${service} -d ${selectedDomain} -d "*.${selectedDomain}" --force`
```
Comment (songz) [inline src/api/admin.ts]: when you type this into the command line, it only creates one cert. Here's what I think we need to do:
```
const { stderr } = await exec(
  `${envVars} ./acme.sh/acme.sh --issue --dns ${service} -d ${selectedDomain} --force`
)
... await exec(
  `${envVars} ./acme.sh/acme.sh --issue --dns ${service} -d *.${selectedDomain} --force`
)
```
